### ISSUE TITLE
[历史博客]CSS：关于em和rem的一些小实验

### ISSUE THREAD

**Issue by z0nka1** [z0nka1/blog#40]
> 来自我的早期博客，出处：[https://z0nka1.github.io/](https://z0nka1.github.io/)

今天我用em和rem做了一些小实验，总结了几个规律，接下来我就和你分享下。

### 1.rem是相对于html标签的单位

这一点毋庸置疑！

HTML:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<body>
  <div id="parent">
    <div id="child">child</div>
  </div>
</body>
</html>
```

CSS:

```css
html {
  font-size: 10px;
}

body {
  font-size: 50px;
}

#parent {
  height:150px;
  background:#9cd4d8;
  font-size: 20px;
}

#child {
  background: #cbb9ff;
  font-size: 2rem;
}
```

效果如下图，child的`font-size`结果是`20px`，是按照`html`的`font-size`来设置的，不是`body`，也不是父元素。

![](https://z0nka1.github.io//assets/img/no_subject/em_rem_01.png)

### 2.font-size的情况下，em是根据最近的祖先元素来设置的

把样式改成下面这样：

```css
html {
  font-size: 10px;
}

body {
  font-size: 50px;
}

#parent {
  height:150px;
  background:#9cd4d8;
  font-size: 20px;
}

#child {
  background: #cbb9ff;
  font-size: 2em; /* <--- 这里用em代替了rem */
}
```

这样之后`child`的`font-size`就变成了`parent`的两倍，也就是40px。

![](https://z0nka1.github.io//assets/img/no_subject/em_rem_02.png)

如果把`parent`的`font-size`注释掉，那么`child`的`font-size`就会根据上一个有定义`font-size`的祖先元素（在这个例子里是`body`）来设置。

![](https://z0nka1.github.io//assets/img/no_subject/em_rem_03.png)

### 3.当width用em作单位时是根据当前元素或者祖先元素的font-size值来计算的

这里分两种情况：

**注意：以下两种情况都是在width以em作为单位的前提下**

#### 情况一：当前元素设置了font-size

如果当前元素设置了`font-size`，那么用`em`作为单位的`width`就会根据这个`font-size`的最终值来计算。

```css
html {
  font-size: 10px;
}

body {
  font-size: 50px;
  padding-top: 100px;
}

#parent {
  height:150px;
  background:#9cd4d8;
  font-size: 20px;
}

#child {
  background: #cbb9ff;
  font-size: 30px;
  width: 2em;
}
```

这里`child`的`font-size`为30px，`width`设置为2em，那么最终`child`的长度为 2 × 30px = 60px：

![](https://z0nka1.github.io//assets/img/no_subject/em_rem_04.png)

font-size使用其他单位时结论也是一样的：

```css
#child {
  background: #cbb9ff;
  font-size: 2rem;
  width: 2em;
}
```

这时2rem就是20px，最终长度就是 2 × 20px = 40px：

![](https://z0nka1.github.io//assets/img/no_subject/em_rem_05.png)

#### 情况二：当前元素未设置font-size

在这种情况下，`width`会根据最近的设置了`font-size`的祖先元素来计算。

```css
html {
  font-size: 10px;
}

body {
  font-size: 50px;
  padding-top: 100px;
}

#parent {
  height:150px;
  background:#9cd4d8;
  font-size: 20px;
}

#child {
  background: #cbb9ff;
  /* font-size: 2rem; */
  width: 2em;
}
```

这里把`child`的`font-size`注释掉，`child`的`width`就会根据最近的设置了`font-size`的祖先元素（在这里是`parent`）来计算：

![](https://z0nka1.github.io//assets/img/no_subject/em_rem_06.png)

如果把`parent`的`font-size`也注释掉

```css
html {
  font-size: 10px;
}

body {
  font-size: 50px;
  padding-top: 100px;
}

#parent {
  height:150px;
  background:#9cd4d8;
  /* font-size: 20px; */
}

#child {
  background: #cbb9ff;
  /* font-size: 2rem; */
  width: 2em;
}
```

`child`的`width`就会根据上一级设置了`font-size`的祖先元素（在这里是`body`）来计算：

![](https://z0nka1.github.io//assets/img/no_subject/em_rem_07.png)

仔细观察本节的几张图片你会发现，不管哪种情况，当以`em`作为`width`的单位时，`width`都是根据当前元素的`font-size`来计算的，因为`font-size`会从祖先元素继承而来。在这个例子里，我们把`child`的`width`设置为2em，所以`child`的长度永远等于child的font-size × 2。
